class RealOoTScenarioTemplate:
    """Real OoT scenario templates mined from actual source code"""
    
    @staticmethod
    def get_enemy_scenarios() -> List[str]:
        return [
            "Create a En Am actor that armos",
            "Create a En Anubice Fire actor that anubis fire attack",
            "Create a En Anubice actor that anubis body",
            "Create a En Attack Niw actor that attacking cucco, not solid",
            "Create a En Ba actor that tentacle from inside lord jabu-jabu",
            "Create a En Bb actor that bubble (flying skull enemy)",
            "Create a En Bdfire actor that king dodongo's fire breath",
            "Create a En Bili actor that biri (small jellyfish-like enemy)",
            "Create a En Brob actor that flobbery muscle block (jabu-jabu's belly)",
            "Create a En Bw actor that torch slug",
            "Create a En Bx actor that jabu-jabu electrified tentacle",
            "Create a En Dekunuts actor that mad scrub",
            "Create a En Dh actor that dead hand",
            "Create a En Dha actor that dead hand's hand",
            "Create a En Dodojr actor that baby dodongo",
            "Create a En Fd actor that flare dancer (enflamed form)",
            "Create a En Firefly actor that keese (normal, fire, ice)",
            "Create a En Floormas actor that floormaster",
            "Create a En Fw actor that flare dancer core",
            "Create a En Geldb actor that gerudo fighter",
            "Create a En Goma actor that gohma larva",
            "Create a En Hintnuts actor that hint deku scrubs (deku tree)",
            "Create a En Ik actor that iron knuckle",
            "Create a En Mb actor that moblins",
            "Create a En Po Field actor that field poe",
            "Create a En Po Sisters actor that forest temple four poe sisters",
            "Create a En Poh actor that graveyard poe",
            "Create a En Rd actor that redead and gibdo",
            "Create a En Rr actor that like like",
            "Create a En Sb actor that shellblade",
            "Create a En Shopnuts actor that deku salesman - attack phase",
            "Create a En Skb actor that stalchild",
            "Create a En Skjneedle actor that skullkid needle attack",
            "Create a En St actor that skulltula (normal, big, invisible)",
            "Create a En Test actor that stalfos",
            "Create a En Tite actor that tektite",
            "Create a En Tp actor that electric tailpasaran",
            "Create a En Vali actor that bari (big jellyfish)",
            "Create a En Vm actor that beamos",
            "Create a En Wallmas actor that wallmaster (ceiling monster)",
            "Create a En Weiyer actor that stinger (water)",
            "Create a En Wf actor that wolfos (normal and white)",
            "Create a En Yukabyun actor that flying floor tile",
            "Create a En Zf actor that lizalfos and dinolfos",
            "Create a Obj Roomtimer actor that starts timer 1 with a value specified in params",
            "Implement a En Bigokuta actor following OoT decompilation patterns",
            "Implement a En Bubble actor following OoT decompilation patterns",
            "Implement a En Crow actor following OoT decompilation patterns",
            "Implement a En Dekubaba actor following OoT decompilation patterns",
            "Implement a En Dodongo actor following OoT decompilation patterns",
            "Implement a En Eiyer actor following OoT decompilation patterns",
            "Implement a En Encount2 actor following OoT decompilation patterns",
            "Implement a En Fd Fire actor following OoT decompilation patterns",
            "Implement a En Fire Rock actor following OoT decompilation patterns",
            "Implement a En Fz actor following OoT decompilation patterns",
            "Implement a En Karebaba actor following OoT decompilation patterns",
            "Implement a En Ny actor following OoT decompilation patterns",
            "Implement a En Okuta actor following OoT decompilation patterns",
            "Implement a En Peehat actor following OoT decompilation patterns",
            "Implement a En Skj actor following OoT decompilation patterns",
        ]
    
    @staticmethod
    def get_npc_scenarios() -> List[str]:
        return [
            "Create a Bg Zg actor that metal bars (ganon's castle)",
            "Create a Demo Ec actor that credits revelers in lon lon",
            "Create a Demo Ext actor that magic vortex in silver gauntlets cutscene",
            "Create a Demo Go actor that gorons (cutscene)",
            "Create a Demo Im actor that impa",
            "Create a Demo Sa actor that saria (cutscene)",
            "Create a En Ani actor that kakariko roof guy",
            "Create a En Cow actor that cow",
            "Create a En Daiku Kakariko actor that kakariko village carpenters",
            "Create a En Diving Game actor that diving minigame",
            "Create a En Dnt Jiji actor that forest stage scrub leader",
            "Create a En Dog actor that dog",
            "Create a En Ds actor that potion shop granny",
            "Create a En Fu actor that windmill man",
            "Create a En Gb actor that poe seller",
            "Create a En Ge1 actor that white-clothed gerudo",
            "Create a En Ge2 actor that purple-clothed gerudo",
            "Create a En Ge3 actor that gerudo giving you membership card",
            "Create a En Gm actor that medi-goron",
            "Create a En Guest actor that happy mask shop customer",
            "Create a En Heishi1 actor that courtyard guards",
            "Create a En Heishi2 actor that hyrulian guards",
            "Create a En Heishi3 actor that hyrule castle guard",
            "Create a En Hs actor that carpenter's son",
            "Create a En Hs2 actor that carpenter's son (child link version)",
            "Create a En Hy actor that hylian npcs",
            "Create a En Js actor that magic carpet salesman",
            "Create a En Jsjutan actor that magic carpet man's carpet",
            "Create a En Kakasi actor that pierre the scarecrow",
            "Create a En Kakasi3 actor that bonooru the scarecrow",
            "Create a En Ko actor that kokiri children, and fado",
            "Create a En Kz actor that king zora",
            "Create a En Ma1 actor that child malon",
            "Create a En Ma2 actor that adult malon (stables / ranch pre-epona)",
            "Create a En Ma3 actor that adult malon (ranch)",
            "Create a En Md actor that mido",
            "Create a En Mk actor that lakeside professor",
            "Create a En Mm actor that running man (child)",
            "Create a En Mm2 actor that running man (adult)",
            "Create a En Ms actor that magic bean salesman",
            "Create a En Mu actor that haggling townspeople",
            "Create a En Nb actor that nabooru",
            "Create a En Niw Girl actor that girl that chases a cuckoo around in hyrule market and kakariko village",
            "Create a En Oe2 actor that blue navi target spot",
            "Create a En Owl actor that owl",
            "Create a En Po Relay actor that dampé's ghost",
            "Create a En Rl actor that rauru",
            "Create a En Ru1 actor that ruto (child)",
            "Create a En Ru2 actor that adult ruto",
            "Create a En Sth actor that uncursed house of skulltula people",
            "Create a En Ta actor that talon",
            "Create a En Takara Man actor that treasure chest game man",
            "Create a En Tg actor that dancing couple",
            "Create a En Tk actor that dampe npc from "dampe's heart-pounding gravedigging tour"",
            "Create a En Toryo actor that boss carpenter",
            "Create a En Tr actor that koume and kotake",
            "Create a En Xc actor that sheik",
            "Create a En Zl1 actor that child princess zelda (at window)",
            "Create a En Zl2 actor that adult zelda (cutscenes)",
            "Create a En Zl4 actor that child princess zelda",
            "Create a En Zo actor that zora",
            "Create a Fishing actor that fishing pond elements (owner, fish, props, effects...)",
            "Create a Item Inbox actor that zelda's magic effect when opening gates in castle collapse",
            "Create a Obj Dekujr actor that deku tree sprout",
            "Implement a Demo Du actor following OoT decompilation patterns",
            "Implement a Demo Ik actor following OoT decompilation patterns",
            "Implement a Eff Dust actor following OoT decompilation patterns",
            "Implement a En Bom Bowl Man actor following OoT decompilation patterns",
            "Implement a En Cs actor following OoT decompilation patterns",
            "Implement a En Daiku actor following OoT decompilation patterns",
            "Implement a En Du actor following OoT decompilation patterns",
            "Implement a En Fr actor following OoT decompilation patterns",
            "Implement a En Go actor following OoT decompilation patterns",
            "Implement a En Go2 actor following OoT decompilation patterns",
            "Implement a En Heishi4 actor following OoT decompilation patterns",
            "Implement a En In actor following OoT decompilation patterns",
            "Implement a En Niw Lady actor following OoT decompilation patterns",
            "Implement a En Ossan actor following OoT decompilation patterns",
            "Implement a En Sa actor following OoT decompilation patterns",
            "Implement a En Ssh actor following OoT decompilation patterns",
            "Implement a En Sw actor following OoT decompilation patterns",
            "Implement a En Syateki Man actor following OoT decompilation patterns",
        ]
    
    @staticmethod
    def get_item_scenarios() -> List[str]:
        return [
            "Create a Arrow Fire actor that fire arrow. spawned as a child of a normal arrow.",
            "Create a Arrow Ice actor that ice arrow. spawned as a child of a normal arrow.",
            "Create a Arrow Light actor that light arrow. spawned as a child of a normal arrow.",
            "Create a Bg Gate Shutter actor that death mountain trail gate",
            "Create a Bg Spot15 Saku actor that hyrule castle gate",
            "Create a Demo Shd actor that bongo bongo's shadow",
            "Create a Door Ana actor that grotto",
            "Create a Door Gerudo actor that metal grate door",
            "Create a Elf Msg actor that readable navi call spot",
            "Create a En Arrow actor that arrow, deku seed, and deku nut projectile",
            "Create a En Butte actor that butterfly",
            "Create a En Eg actor that triggers a void out (used in the tower collapse sequence?)",
            "Create a En Elf actor that fairy",
            "Create a En Fish actor that fish",
            "Create a En Ice Hono actor that the various types of blue fire",
            "Create a En Insect actor that bugs",
            "Create a En Jj actor that lord jabu-jabu",
            "Create a En Light actor that flame",
            "Create a En Part actor that effect spawner for enemies' death",
            "Create a En Si actor that gold skulltula token",
            "Create a En Viewer actor that cutscene actors",
            "Create a En Wonder Talk2 actor that dialog spot",
            "Create a End Title actor that "the end" message",
            "Create a Item Ocarina actor that ocarina of time",
            "Create a Item Shield actor that deku shield",
            "Create a Magic Dark actor that nayru's love",
            "Create a Magic Fire actor that din's fire",
            "Create a Magic Wind actor that farore's wind",
            "Create a Mir Ray actor that reflectable light beam and reflections",
            "Create a Obj Makekinsuta actor that skulltula sprouting from bean spot",
            "Create a Obj Timeblock actor that song of time block",
            "Create a Obj Warp2Block actor that navi infospot (green, time block)",
            "Create a Oceff Spot actor that sun's song effect",
            "Create a Oceff Storm actor that song of storms effect",
            "Create a Oceff Wipe actor that zelda's lullaby and song of time ocarina effect",
            "Create a Oceff Wipe2 actor that epona's song effect",
            "Create a Oceff Wipe3 actor that saria's song effect",
            "Create a Oceff Wipe4 actor that scarecrow's song and an unused ocarina effect",
            "Create an actor for environmental effects",
            "Create an actor that spawns a chest with the appropriate contents then dies. used in grottos.",
            "Create an actor that spawns fish, bug, butterfly",
            "Implement a Arms Hook actor following OoT decompilation patterns",
            "Implement a Demo Kekkai actor following OoT decompilation patterns",
            "Implement a Demo Tre Lgt actor following OoT decompilation patterns",
            "Implement a Door Warp1 actor following OoT decompilation patterns",
            "Implement a Efc Erupc actor following OoT decompilation patterns",
            "Implement a En M Thunder actor following OoT decompilation patterns",
            "Implement an actor that manages the storm created when playing song of storms",
        ]
    
    @staticmethod
    def get_object_scenarios() -> List[str]:
        return [
            "Create a Bg Bom Guard actor that bombchu bowling alley walls",
            "Create a Bg Bowl Wall actor that bombchu bowling alley wall",
            "Create a Bg Dy Yoseizo actor that great fairy",
            "Create a Bg Ganon Otyuka actor that falling platform (ganondorf fight)",
            "Create a Bg Gjyo Bridge actor that rainbow bridge outside ganon's castle",
            "Create a Bg Gnd Darkmeiro actor that shadow trial actors (invisible path, clear block, and timer)",
            "Create a Bg Gnd Firemeiro actor that sinking lava platform (ganon's castle)",
            "Create a Bg Gnd Iceblock actor that pushable ice block (inside ganon's castle)",
            "Create a Bg Gnd Nisekabe actor that ganon's castle fake wall",
            "Create a Bg Gnd Soulmeiro actor that web-blocked ceiling hole (inside ganon's castle)",
            "Create a Bg Haka Gate actor that truth spinner puzzle (shadow temple)",
            "Create a Bg Haka Megane actor that shadow temple fake walls",
            "Create a Bg Haka Sgami actor that spinning scythe trap",
            "Create a Bg Haka Water actor that bottom of the well water level changer",
            "Create a Bg Haka Zou actor that statue and wall (shadow temple)",
            "Create a Bg Hidan Curtain actor that flame circle",
            "Create a Bg Ice Objects actor that pushable ice block (ice cavern)",
            "Create a Bg Ice Shutter actor that vertical ice bars (doors) in ice cavern",
            "Create a Bg Ice Turara actor that icicles",
            "Create a Bg Ingate actor that ingo's gates (lon lon ranch)",
            "Create a Bg Jya Block actor that silver block (child link)",
            "Create a Bg Jya Haheniron actor that chunks of iron knucle chair and pillar",
            "Create a Bg Jya Ironobj actor that destructable iron knuckle objects",
            "Create a Bg Menkuri Nisekabe actor that false stone walls (gerudo training grounds)",
            "Create a Bg Mizu Uzu actor that water noise",
            "Create a Bg Po Syokudai actor that golden torch stand (poe sisters)",
            "Create a Bg Spot00 Break actor that broken drawbridge in hyrule field.",
            "Create a Bg Spot01 Idohashira actor that wooden beam above well in kakariko village",
            "Create a Bg Spot05 Soko actor that sacred forest meadow entities",
            "Create a Bg Spot06 Objects actor that lake hylia objects",
            "Create a Bg Spot16 Doughnut actor that death mountain cloud circle",
            "Create a Bg Spot18 Futa actor that the lid to the spinning goron vase.",
            "Create a Bg Toki Swd actor that master sword (contains cutscenes)",
            "Create a Bg Umajump actor that hoppable horse fence",
            "Create a Bg Ydan Maruta actor that rotating spike log and falling ladder in deku tree",
            "Create a Demo 6K actor that sages, balls of light (cutscene)",
            "Create a En Arow Trap actor that an unused trap that reflects arrows.",
            "Create a En Bird actor that an unused brown bird",
            "Create a En Blkobj actor that dark link's illusion room",
            "Create a En Bombf actor that bomb flower",
            "Create a En Changer actor that treasure box shop minigame",
            "Create a En Dnt Demo actor that forest stage minigame",
            "Create a En Dnt Nomal actor that lost woods minigame scrubs",
            "Create a En Dy Extra actor that spiral beams (great fairy fountains)",
            "Create a En Ex Item actor that minigame prize items",
            "Create a En G Switch actor that silver rupees, shooting gallery targets, and horseback archery pots",
            "Create a En Girla actor that shop items",
            "Create a En Gs actor that gossip stone",
            "Create a En Hata actor that wooden post with red cloth",
            "Create a En Ishi actor that small and large gray rocks",
            "Create a En It actor that dampe's minigame digging spot hitboxes",
            "Create a En Kakasi2 actor that pierre the scarecrow spawn",
            "Create a En Kanban actor that cuttable square sign",
            "Create a En Kusa actor that bush",
            "Create a En Mag actor that title screen manager & logo",
            "Create a En Niw actor that cucco",
            "Create a En Nutsball actor that projectile fired by deku scrubs",
            "Create a En Nwc actor that cluster of cucco chicks. unfinished.",
            "Create a En Okarina Tag actor that music staff (ocarina) spot",
            "Create a En Scene Change actor that unknown (broken actor)",
            "Create a En Syateki Niw actor that hopping cucco",
            "Create a En Tana actor that shop shelves",
            "Create a En Tubo Trap actor that flying pot enemy",
            "Create a En Vase actor that an unused, orange pot based on alttp. lacks collision.",
            "Create a En Wall Tubo actor that bombchu bowling alley bullseyes/pits",
            "Create a En Weather Tag actor that proximity activated weather effects",
            "Create a En Wonder Item actor that invisible collectable; used in mq to create "cow" switches",
            "Create a En Wonder Talk actor that checkable spot (green navi)",
            "Create a En Wood02 actor that trees, bushes, leaves",
            "Create a En Yabusame Mark actor that horseback archery target (arrow hitbox)",
            "Create a Item Etcetera actor that collectible items",
            "Create a Obj Blockstop actor that stops blocks and sets relevant flags when the block is in position.",
            "Create a Obj Comb actor that beehive",
            "Create a Obj Hana actor that grave flower",
            "Create a Obj Ice Poly actor that ice / frozen actors",
            "Create a Obj Kibako actor that small wooden box",
            "Create a Obj Makeoshihiki actor that push block puzzle (hardcoded)",
            "Create a Obj Mure2 actor that rock/bush groups",
            "Create a Obj Oshihiki actor that push block",
            "Create a Obj Syokudai actor that torch",
            "Create a Obj Tsubo actor that breakable pot",
            "Create a Shot Sun actor that lake hylia sun hitbox and song of storms fairy spawner",
            "Create a bronze boulder that can be broken with a hammer",
            "Create a rolling boulders that can be broken with a hammer",
            "Create a round, brown, breakable boulder that can be broken with a hammer",
            "Implement a Bg Hidan Fwbig actor following OoT decompilation patterns",
            "Implement a Bg Hidan Kousi actor following OoT decompilation patterns",
            "Implement a Bg Jya Cobra actor following OoT decompilation patterns",
            "Implement a Bg Jya Goroiwa actor following OoT decompilation patterns",
            "Implement a Bg Mizu Shutter actor following OoT decompilation patterns",
            "Implement a Bg Spot16 Bombstone actor following OoT decompilation patterns",
            "Implement a Bg Spot18 Basket actor following OoT decompilation patterns",
            "Implement a Bg Spot18 Shutter actor following OoT decompilation patterns",
            "Implement a Demo Gt actor following OoT decompilation patterns",
            "Implement a En Bom Bowl Pit actor following OoT decompilation patterns",
            "Implement a En Encount1 actor following OoT decompilation patterns",
            "Implement a En Ex Ruppy actor following OoT decompilation patterns",
            "Implement a En Honotrap actor following OoT decompilation patterns",
            "Implement a En Lightbox actor following OoT decompilation patterns",
            "Implement a En Syateki Itm actor following OoT decompilation patterns",
        ]
    
    @staticmethod
    def get_background_scenarios() -> List[str]:
        return [
            "Create a Bg Bdan Objects actor that lord jabu-jabu objects",
            "Create a Bg Ddan Jd actor that rising stone platform (dodongo's cavern)",
            "Create a Bg Ddan Kd actor that falling stairs in dodongo's cavern",
            "Create a Bg Dodoago actor that dodongo head statue in dodongo's cavern",
            "Create a Bg Haka Huta actor that coffin lid",
            "Create a Bg Haka Ship actor that shadow temple ship",
            "Create a Bg Haka Trap actor that shadow temple objects",
            "Create a Bg Haka Tubo actor that shadow temple giant skull jar",
            "Create a Bg Haka actor that gravestone",
            "Create a Bg Heavy Block actor that large block that can only be lifted with golden gauntlets",
            "Create a Bg Hidan Dalm actor that hammerable totem pieces (fire temple)",
            "Create a Bg Hidan Firewall actor that proximity triggered flame wall",
            "Create a Bg Hidan Fslift actor that hookshot elevator",
            "Create a Bg Hidan Hamstep actor that stone steps and platforms (fire temple)",
            "Create a Bg Hidan Hrock actor that huge stone spike platform (fire temple)",
            "Create a Bg Hidan Rock actor that stone blocks (fire temple)",
            "Create a Bg Hidan Rsekizou actor that spinning stone flamethrower",
            "Create a Bg Hidan Sekizou actor that stationary flame thrower statue",
            "Create a Bg Hidan Sima actor that stone platform (fire temple)",
            "Create a Bg Hidan Syoku actor that stone elevator in the fire temple",
            "Create a Bg Ice Shelter actor that red ice",
            "Create a Bg Jya 1Flift actor that shortcut elevator used in the vanilla version of the spirit temple",
            "Create a Bg Jya Amishutter actor that circular metal grate. lifts up when you get close to it.",
            "Create a Bg Jya Bigmirror actor that ceiling mirror and puzzle in spirit temple top rooms",
            "Create a Bg Jya Kanaami actor that climbable grating/bridge (spirit temple)",
            "Create a Bg Jya Lift actor that chain platform (spirit temple)",
            "Create a Bg Jya Megami actor that face of spirit temple goddess statue",
            "Create a Bg Jya Zurerukabe actor that sliding, climbable brick wall",
            "Create a Bg Menkuri Eye actor that eye platform eye switches",
            "Create a Bg Menkuri Kaiten actor that large rotating stone ring used in gerudo training grounds and forest temple.",
            "Create a Bg Mizu Movebg actor that water temple moving objects",
            "Create a Bg Mizu Water actor that water plane in water temple. changes height based on switches 0x1c, 0x1d, 0x1e.",
            "Create a Bg Mjin actor that warp pad",
            "Create a Bg Mori Bigst actor that forest temple falling platform and stalfos fight",
            "Create a Bg Mori Hashigo actor that falling ladder and clasp that holds it. unused.",
            "Create a Bg Mori Hashira4 actor that forest temple gates and rotating pillars",
            "Create a Bg Mori Hineri actor that twisting hallway in forest temple",
            "Create a Bg Mori Idomizu actor that square of water in forest temple well",
            "Create a Bg Mori Kaitenkabe actor that rotating wall in forest temple basement",
            "Create a Bg Mori Rakkatenjo actor that falling ceiling in forest temple",
            "Create a Bg Po Event actor that poe sisters' paintings and puzzle blocks",
            "Create a Bg Pushbox actor that unused (and non functional) pushable block",
            "Create a Bg Relay Objects actor that windmill setpieces",
            "Create a Bg Spot00 Hanebasi actor that hyrule field drawbridge and torches",
            "Create a Bg Spot01 Fusya actor that windmill sails",
            "Create a Bg Spot01 Idomizu actor that kakariko village well water",
            "Create a Bg Spot01 Idosoko actor that stone that blocks the entrance to bottom of the well",
            "Create a Bg Spot01 Objects2 actor that kakariko village set pieces",
            "Create a Bg Spot02 Objects actor that graveyard actors",
            "Create a Bg Spot03 Taki actor that zora's river waterfall",
            "Create a Bg Spot07 Taki actor that zora's domain waterfall and ice",
            "Create a Bg Spot08 Bakudankabe actor that destructible wall (zora's fountain)",
            "Create a Bg Spot08 Iceblock actor that floating ice platforms",
            "Create a Bg Spot11 Bakudankabe actor that destructible wall (desert colossus)",
            "Create a Bg Spot11 Oasis actor that refilling oasis (desert colossus)",
            "Create a Bg Spot12 Gate actor that haunted wasteland gate",
            "Create a Bg Spot15 Rrbox actor that milk crate",
            "Create a Bg Sst Floor actor that bongo bongo's drum",
            "Create a Bg Toki Hikari actor that temple of time windows",
            "Create a Bg Treemouth actor that great deku tree's mouth",
            "Create a Bg Vb Sima actor that volvagia's platform",
            "Create a Bg Ydan Hasi actor that deku tree puzzle elements. water plane and floating block in b1, and 3 blocks on 2f",
            "Create a Bg Ydan Sp actor that webs",
            "Create a Door Killer actor that fake doors which attack player",
            "Create a Door Toki actor that door of time collision",
            "Create a Elf Msg2 actor that targetable navi check spot",
            "Create a En Dns actor that deku salesman - sale phase",
            "Create a En Fhg actor that phantom ganon's horse",
            "Create a En Horse Game Check actor that horseback minigames",
            "Create a En Horse Ganon actor that ganondorf's horse",
            "Create a En Horse Link Child actor that young epona",
            "Create a En Horse Normal actor that non-rideable horses (lon lon ranch and stable)",
            "Create a En Horse Zelda actor that zelda's horse",
            "Create a En Po Desert actor that guide poe (haunted wasteland)",
            "Create a En Pu Box actor that an unused stone cube",
            "Create a En River Sound actor that controls various sounds. includes sound effects and bgms",
            "Create a En Siofuki actor that water spout",
            "Create a En Stream actor that water vortex",
            "Create a En Trap actor that metal spike trap",
            "Create a Obj Bean actor that bean plant spot",
            "Create a Obj Elevator actor that stone elevator",
            "Create a Obj Hsblock actor that stone hookshot target",
            "Create a Obj Kibako2 actor that large crate",
            "Create a Obj Lift actor that square, collapsing platform",
            "Create a Obj Mure3 actor that tower of rupees",
            "Implement a Bg Haka Meganebg actor following OoT decompilation patterns",
            "Implement a Bg Jya Bombchuiwa actor following OoT decompilation patterns",
            "Implement a Bg Mori Elevator actor following OoT decompilation patterns",
            "Implement a Bg Spot09 Obj actor following OoT decompilation patterns",
            "Implement a Bg Spot12 Saku actor following OoT decompilation patterns",
            "Implement a Bg Spot18 Obj actor following OoT decompilation patterns",
            "Implement a Demo Effect actor following OoT decompilation patterns",
            "Implement a Demo Kankyo actor following OoT decompilation patterns",
            "Implement a En Horse actor following OoT decompilation patterns",
            "Implement a bombable bombable wall",
            "Implement a bombable death mountain crater bombable wall",
            "Implement a bombable fire temple bombable walls and floors",
            "Implement a bombable spirit temple top room bombable wall",
            "Implement a bombable water temple bombable walls",
        ]
    
    @staticmethod
    def get_effect_scenarios() -> List[str]:
        return [
        ]
    
    @staticmethod
    def get_player_scenarios() -> List[str]:
        return [
        ]
    
    @staticmethod
    def get_misc_scenarios() -> List[str]:
        return [
            "Create a Bg Bdan Switch actor that switches inside lord jabu-jabu",
            "Create a Bg Spot17 Funen actor that crater smoke cone",
            "Create a Boss Fd actor that volvagia, flying form",
            "Create a Boss Fd2 actor that volvagia, hole form",
            "Create a Boss Ganondrof actor that phantom ganon",
            "Create a Boss Goma actor that gohma",
            "Create a Boss Mo actor that morpha",
            "Create a Boss Sst actor that bongo bongo",
            "Create a Boss Va actor that barinade",
            "Create a Demo Geff actor that ganon's lair rubble fragment",
            "Create a Demo Gj actor that ganon battle rubble.",
            "Create a Door Shutter actor that sliding doors, phantom ganon room bars, gohma room rock slab",
            "Create a En Bom actor that bomb",
            "Create a En Boom actor that thrown boomerang. actor spawns when thrown and is killed when caught.",
            "Create a En Door actor that doors with handles",
            "Create a En Fhg Fire actor that phantom ganon's lighting attack",
            "Create a En Ganon Mant actor that ganondorf's cape",
            "Create a En Ganon Organ actor that the organ that ganondorf plays in the cutscene before the fight. includes carpet and scenery as well.",
            "Create a En M Fire1 actor that deku nut hitbox",
            "Create a En Reeba actor that leever",
            "Create a En Torch2 actor that dark link",
            "Create a En Vb Ball actor that volvagia's rocks and bones",
            "Create a En Zl3 actor that adult zelda",
            "Create a Item B Heart actor that heart container",
            "Create a Obj Lightswitch actor that sun emblem trigger (spirit temple)",
            "Create a Obj Switch actor that switches",
            "Create a Player actor that link",
            "Create an actor that spawns and manages the anubis enemy",
            "Implement a Bg Toki Swd Cutscene Data 1 actor following OoT decompilation patterns",
            "Implement a Bg Toki Swd Cutscene Data 2 actor following OoT decompilation patterns",
            "Implement a Bg Toki Swd Cutscene Data 3 actor following OoT decompilation patterns",
            "Implement a Bg Treemouth Cutscene Data actor following OoT decompilation patterns",
            "Implement a Boss Dodongo Data.Inc actor following OoT decompilation patterns",
            "Implement a Boss Dodongo actor following OoT decompilation patterns",
            "Implement a Boss Fd Colchk.Inc actor following OoT decompilation patterns",
            "Implement a Boss Fd2 Colchk.Inc actor following OoT decompilation patterns",
            "Implement a Boss Ganon actor following OoT decompilation patterns",
            "Implement a Boss Ganon2 actor following OoT decompilation patterns",
            "Implement a Boss Mo Colchk.Inc actor following OoT decompilation patterns",
            "Implement a Boss Sst Colchk.Inc actor following OoT decompilation patterns",
            "Implement a Boss Tw actor following OoT decompilation patterns",
            "Implement a Demo Du Cutscene Data.Inc actor following OoT decompilation patterns",
            "Implement a Demo Im Cutscene Data.Inc actor following OoT decompilation patterns",
            "Implement a Demo Kankyo Cutscene Data1 actor following OoT decompilation patterns",
            "Implement a Demo Kankyo Cutscene Data2 actor following OoT decompilation patterns",
            "Implement a Demo Kankyo Cutscene Data3 actor following OoT decompilation patterns",
            "Implement a Demo Kankyo Cutscene Data4 actor following OoT decompilation patterns",
            "Implement a Demo Kankyo Cutscene Data5 actor following OoT decompilation patterns",
            "Implement a Demo Kankyo Cutscene Data6 actor following OoT decompilation patterns",
            "Implement a Demo Kankyo Cutscene Data7 actor following OoT decompilation patterns",
            "Implement a Demo Kankyo Cutscene Data8 actor following OoT decompilation patterns",
            "Implement a Demo Sa Cutscene Data.Inc actor following OoT decompilation patterns",
            "Implement a En Bom Chu actor following OoT decompilation patterns",
            "Implement a En Box actor following OoT decompilation patterns",
            "Implement a En Clear Tag actor following OoT decompilation patterns",
            "Implement a En Holl actor following OoT decompilation patterns",
            "Implement a En Jj Cutscene Data.Inc actor following OoT decompilation patterns",
            "Implement a En Kanban Gfx.Inc actor following OoT decompilation patterns",
            "Implement a En Nb Cutscene Data.Inc actor following OoT decompilation patterns",
            "Implement a En Okarina Tag Cutscene Data actor following OoT decompilation patterns",
            "Implement a En Ru1 Cutscene Data.Inc actor following OoT decompilation patterns",
            "Implement a En Ru2 Cutscene Data.Inc actor following OoT decompilation patterns",
            "Implement a En Sda actor following OoT decompilation patterns",
            "Implement a En Zl1 Camera Data.Inc actor following OoT decompilation patterns",
            "Implement a En Zl1 Cutscene Data actor following OoT decompilation patterns",
            "Implement a En Zl4 Cutscene Data.Inc actor following OoT decompilation patterns",
        ]
